version: '3'

services:
  redis:
    image: redis:latest
    networks:
      - EasyCreater-network
    
  mysql:
    image: mysql:latest
    # 确保与config.yaml中填写的信息一致
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: demo
      MYSQL_PASSWORD: 123456
    networks:
      - EasyCreater-network

  frontend:
    build:
      context: ./fe
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - EasyCreater-network

  backend:
    build:
      context: ./be
    ports:
      - "8888:8888"
    volumes:
      - ./be/config/config.yaml:/EasyCreater/config/config.yaml
    depends_on:
      - mysql
      - redis
    networks:
      - EasyCreater-network

networks:
  EasyCreater-network:
    driver: bridge
