/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElUpload: typeof import('element-plus/es')['ElUpload']
}
