apiVersion: v1
kind: Service
metadata:
  name: easycreater-be
  namespace: default
spec:
  selector:
    app: easycreater-be
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: easycreater-fe
  namespace: default
spec:
  type: NodePort
  selector:
    app: easycreater-fe
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: easycreater-mysql
  namespace: default
spec:
  selector:
    app: easycreater-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

