name: Build and Push Image

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag the image with(such as v1.0.0)'
        required: false
        type: string

jobs:
  analyze:
    name: sonar-analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    
  build-and-push-backend:
    runs-on: ubuntu-latest
    environment:
      name: registry-secret
    env:
      IMAGE_REGISTRY_SERVICE: ${{ vars.IMAGE_REGISTRY_SERVICE || 'docker.io' }}
      IMAGE_BE_REPOSITORY: ${{ vars.IMAGE_REPOSITORY || 'beatrueman/easycreater-fe' }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

    steps:
    - uses: actions/checkout@v4

    # 登录仓库
    - name: Login to registry 
      uses: docker/login-action@v3
      with:
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_PASSWORD }}

    # 构建镜像
    - name: Build the image
      run: |
        docker build be/ -f be/Dockerfile --tag ${{ env.IMAGE_REGISTRY_SERVICE }}/${{ env.IMAGE_BE_REPOSITORY }}:${{ inputs.version || github.ref_name }}

    # 推送镜像
    - name: Push the image
      run: docker push ${{ env.IMAGE_REGISTRY_SERVICE }}/${{ env.IMAGE_BE_REPOSITORY }}:${{ inputs.version || github.ref_name }}
  build-and-push-frontend:
    runs-on: ubuntu-latest
    environment:
      name: registry-secret
    env:
      IMAGE_REGISTRY_SERVICE: ${{ vars.IMAGE_REGISTRY_SERVICE || 'docker.io' }}
      IMAGE_FE_REPOSITORY: ${{ vars.IMAGE_REPOSITORY || 'beatrueman/easycreater-be' }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

    steps:
    - uses: actions/checkout@v4

    # 登录仓库
    - name: Login to registry 
      uses: docker/login-action@v3
      with:
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_PASSWORD }}

    # 构建镜像
    - name: Build the image
      run: |
        docker build fe/ -f fe/Dockerfile --tag ${{ env.IMAGE_REGISTRY_SERVICE }}/${{ env.IMAGE_FE_REPOSITORY }}:${{ inputs.version || github.ref_name }}

    # 推送镜像
    - name: Push the image
      run: docker push ${{ env.IMAGE_REGISTRY_SERVICE }}/${{ env.IMAGE_FE_REPOSITORY }}:${{ inputs.version || github.ref_name }}
    