# 通义千问 token
token: ""

# 阿里云 oss 存储凭据
OSS:
  Endpoint: ""
  AccessKey: ""
  SecretKey: ""
  BucketName: ""

# 管理员账户
username: "admin"
password: "123456"
email: "1"
phone: "1"

# MySQL数据库配置
MySQL:
  host: mysql
  port: 3306
  database: "demo"
  user: "root"
  password: "123456"
