# 通义千问 token
token: "sk-70afc0771fc44f01a42ed73e983a6547"

# 阿里云 oss 存储凭据
OSS:
  Endpoint: "https://oss-cn-beijing.aliyuncs.com"
  AccessKey: "LTAI5tEeRtTToKy6ZcR7e343"
  SecretKey: "EfLjQGXI4npm 1AtJOCEDffoL3hOoXW8cD"
  BucketName: "yiiong"21

# 管理员账户
username: admin
password: 123456
email: 1783172311@qq.com
phone: 15592282002

# MySQL数据库配置
MySQL:
  host: 192.168.218.140
  port: 3306
  database: demo
  user: root
  password: 123456

# Redis配置
Redis:
  host: 192.168.10.104
  port: 63790
  password: 123456
  DB: 0
